config/routes.rb
EasyShoppingList::Application.routes.draw do
  get "recipe_list/create"

  resources :recipes
  resources :recipe_lists
  resources :potential_words
  resources :shopping_lists
  match '/upload_recipe', to: 'recipes#new'
  match '/parserecipe', to: 'recipe_list#create'
  match '/delete_potential_word', to: 'potential_words#delete'
  match '/show_shopping_list', to: 'shopping_lists#show'
  match '/add_to_shopping_list', to: 'shopping_lists#add_to_shopping_list'
  match '/remove_from_shopping_list', to: 'shopping_lists#remove_from_shopping_list'
  match '/make_certain', to: 'potential_words#make_certain'

  root to:'recipes#index'

end

app/models/shopping_list.rb
# == Schema Information
#
# Table name: shopping_lists
#
#  id   :integer          not null, primary key
#  name :string(255)
#

class ShoppingList < ActiveRecord::Base
  attr_accessible :name, :id
  has_many :recipe_lists, :through => :shopping_lists_recipe_lists
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController

	def show
		@shopping_list = ShoppingList.first()
		if @shopping_list.nil?
			@shopping_list = ShoppingList.create()
		end
		shopping_lists_recipe_lists = ShoppingListsRecipeLists.find_all_by_shopping_list_id(@shopping_list.id)
		@recipe_lists = Array.new
		shopping_lists_recipe_lists.each do |list_list|
			@recipe_lists.push(RecipeList.find(list_list.recipe_list_id))
		end
		@ingredients = Array.new()
		@recipe_lists.each do |recipe|
			logger.debug "recipe id: #{recipe.id}"
			@ingredients += CertainWord.find_all_by_recipe_list_id(recipe.id)
			@ingredients += PotentialWord.find_all_by_recipe_list_id(recipe.id)
		end
		@ingredients = remove_duplicate_ingredients(@ingredients)
	end


	def add_to_shopping_list
		logger.debug "ATTEMPTING TO ADD RECIPE LIST: #{params[:recipe_list_id]}"
		@shopping_list = get_shopping_list
		logger.debug "#{@shopping_list.id}"
		shooping_lists_recipe_list = ShoppingListsRecipeLists.create(:recipe_list_id => params[:recipe_list_id], :shopping_list_id => @shopping_list.id)
		redirect_to @shopping_list
	end

	def remove_from_shopping_list
		logger.debug "Attempting to remove recipe list: #{params}"
		@shopping_list = get_shopping_list
		recipe_list_id = params[:recipe]
		ShoppingListsRecipeLists.find(:first, :conditions => ["recipe_list_id = ? and shopping_list_id = ?", recipe_list_id, @shopping_list.id]).destroy
		redirect_to @shopping_list
	end

	private 
		def get_shopping_list
			shopping_list = ShoppingList.first()
			if shopping_list.nil?
				shopping_list = ShoppingList.create()
			end
			return shopping_list
		end

		def remove_duplicate_ingredients(array)
			unique_ingredients = Array.new
			existing_ingredients = Array.new
			array.each do |value|
				if !existing_ingredients.include? value.word
					unique_ingredients.push value
					existing_ingredients.push value.word
				end
			end
			return unique_ingredients
		end

end

app/helpers/shopping_list_helper.rb
module ShoppingListHelper	
end

app/views/shopping_lists/new.html.erb
CREATE THIS ONE
<%= form_for @shopping_list do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.submit "Create Shopping List" %>
<% end %>

app/views/shopping_lists/show.html.erb
<div class="shopping-list">
	<ul>
		<li>
			<h1>
				Recipes:
				<%= @recipe_lists.count %>
			</h1>
		</li>
		<% @recipe_lists.each do |recipe| %>
			<li>
				<span class="recipe-name">
					<%= recipe.recipe_name %>
				</span>

				<%= button_to "Remove From List", remove_from_shopping_list_path(:params => {:recipe => recipe}) %>
			</li>
		<% end %>
	</ul>
	<br>
	<ul>
		<li>
			<h1>
				ingredients:
				<%= @ingredients.count %>
			<h1>
		</li>
		<% @ingredients.each do |ingredient| %>
			<li class="ingredient" onclick="toggleStrike(this)">
				<%= ingredient.word %>
			</li>
		<% end %>
	</ul>
<div>